# Generated by Django 5.2.7 on 2025-11-19 00:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(db_column='nombre_estado', max_length=50)),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=100, null=True)),
                ('id_estado', models.IntegerField(blank=True, db_column='id_estado', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipopago', models.CharField(db_column='tipopago', max_length=50)),
                ('id_estado', models.IntegerField(db_column='id_estado')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('alumno', 'Alumno'), ('cajero', 'Cajero'), ('admin', 'Admin')], default='alumno', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_alumno', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_alumno', models.CharField(blank=True, max_length=100, null=True)),
                ('DNI', models.IntegerField(blank=True, null=True)),
                ('domicilio_alumno', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_alumno', models.IntegerField(blank=True, null=True)),
                ('email_alumno', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(max_length=255)),
                ('aprobado', models.BooleanField(default=False)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('recargo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('detalle_planes_pago_cuota_alumno', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_registro', models.IntegerField(default=1)),
                ('id_cupon_pago_cuota', models.IntegerField(blank=True, null=True)),
                ('id_tipo_pago', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('alumno', models.ForeignKey(db_column='alumno_id', on_delete=django.db.models.deletion.CASCADE, to='app.alumno')),
                ('estado_pago', models.ForeignKey(db_column='estado_pago', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.estadopago')),
                ('usuario_registra', models.ForeignKey(db_column='usuario_registra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
                ('usuario_valida', models.ForeignKey(blank=True, db_column='usuario_valida', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_validados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.CharField(max_length=100)),
                ('aprobado', models.BooleanField(default=False)),
                ('id_pago', models.BigIntegerField(blank=True, db_column='id_pago', null=True)),
                ('nro_comprobante', models.IntegerField(blank=True, null=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('id_cuponpago_cuota', models.IntegerField(blank=True, null=True)),
                ('importe', models.IntegerField(blank=True, null=True)),
                ('user_valida', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_validado', models.DateField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
                ('id_estado', models.IntegerField(blank=True, db_column='id_estado', null=True)),
                ('urlarchivo', models.CharField(blank=True, max_length=255, null=True)),
                ('pago', models.ForeignKey(db_column='pago_id', on_delete=django.db.models.deletion.CASCADE, to='app.pago')),
            ],
        ),
        migrations.CreateModel(
            name='PlanPagoAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plan', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('id_alumno', models.IntegerField(blank=True, null=True)),
                ('id_cuota', models.IntegerField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_ini', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.alumno')),
            ],
        ),
        migrations.AddField(
            model_name='pago',
            name='id_plan_pago_alumno',
            field=models.ForeignKey(blank=True, db_column='id_plan_pago_alumno', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.planpagoalumno'),
        ),
        migrations.AddField(
            model_name='pago',
            name='tipos_pago',
            field=models.ForeignKey(db_column='tipos_pago', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tipopago'),
        ),
    ]
