# Generated by Django 5.2.7 on 2025-11-19 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_pago_alumno_alter_pago_estado_pago_and_more'),
    ]

    operations = [
    ]
