# Generated by Django 5.2.7 on 2025-11-21 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20251118_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadopago',
            name='color',
            field=models.CharField(blank=True, db_column='color', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_ven',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado_pago',
            field=models.ForeignKey(blank=True, db_column='estado_pago_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.estadopago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='id_plan_pago_alumno',
            field=models.ForeignKey(blank=True, db_column='id_plan_pago_alumno_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.planpagoalumno'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipos_pago',
            field=models.ForeignKey(blank=True, db_column='tipos_pago_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tipopago'),
        ),
    ]
