# Generated by Django 5.2.7 on 2025-11-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_estadopago_color_pago_fecha_ven_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='urlarchivo',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
    ]
