# Generated by Django 5.2.7 on 2025-11-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_comprobante_urlarchivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='cupon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
