# Generated by Django 5.2.7 on 2025-11-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_comprobante_cupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='archivo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
