# Generated by Django 5.2.7 on 2025-11-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_comprobante_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobante',
            name='id',
        ),
        migrations.AddField(
            model_name='comprobante',
            name='id_comprobante',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
