# Generated by Django 5.2.7 on 2025-11-21 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_comprobante_id_comprobante_id_comprobante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobante',
            name='id_pago',
        ),
        migrations.AddField(
            model_name='comprobante',
            name='id_tipo_pago',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='pago',
            field=models.ForeignKey(db_column='id_pago', on_delete=django.db.models.deletion.CASCADE, to='app.pago'),
        ),
    ]
