# Generated by Django 5.2.7 on 2025-11-21 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_comprobante_id_pago_comprobante_id_tipo_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobante',
            name='id_tipo_pago',
        ),
    ]
