# Generated by Django 5.2.7 on 2025-11-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_comprobante_id_tipo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='id_tipo_pago',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
