# Generated by Django 5.2.7 on 2025-11-21 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_comprobante_id_tipo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobante',
            name='id_tipo_pago',
        ),
        migrations.AddField(
            model_name='comprobante',
            name='tipopago',
            field=models.ForeignKey(blank=True, db_column='id_tipo_pago', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tipopago'),
        ),
    ]
