# Generated by Django 5.2.7 on 2025-11-21 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_comprobante_id_tipo_pago_comprobante_tipopago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobante',
            name='id_estado',
        ),
        migrations.AddField(
            model_name='comprobante',
            name='estadopago',
            field=models.ForeignKey(blank=True, db_column='id_estado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.estadopago'),
        ),
    ]
