# Generated by Django 5.2.7 on 2025-11-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_comprobante_id_estado_comprobante_estadopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='pasarela',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
